baseURL = 'https://dice-nx.dev/'
languageCode = 'en-us'
title = 'DICE-nx'
theme = "dice-nx-hi"
relativeURLS = true

[params]
downloadURL = "https://github.com/dice-nx/dice-nx/releases/download/3.20.0/DICE-nx-3.20.0.lha"

[permalinks]
posts = "/news/:year/:title/"

[menus]
  [[menus.main]]
    name = 'News'
    pageRef = '/posts/'  # this is referring to the *filesystem* path. When rendered, it will be /news/
    weight = 50

[module]
    [[module.mounts]]
        source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
        target = "assets/js/bootstrap.bundle.min.js"
    [[module.mounts]]
        source = "node_modules/bootstrap-icons/bootstrap-icons.svg"
        target = "static/bootstrap-icons.svg"
