name = 'DICE-NX-lo'
license = 'BSD'
licenselink = 'https://opensource.org/license/bsd-3-clause'
description = 'DICE-NX low tech theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dice-nx/dice-nx-website/themes/dice-nx-lo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Richard Downer'
  homepage = 'https://github.com/dice-nx'
